
### 创建bucket服务

GET http://localhost:8001/api/oss/create?bucketName=oss-dev2


### upload上传文件服务功能控制


POST http://localhost:8001/api/oss/upload?bucketName=oss-dev
# Request Headers
Cache-Control: no-cache
Content-Type: multipart/form-data; boundary=WebAppBoundary

# name = 参数名
# filename = 文件名
--WebAppBoundary
Content-Disposition: form-data; name="file";filename="R-C.jpeg"
Content-Type: multipart/form-data
# 本地文件地址
< /Users/linglingdai/opt/minio/R-C.jpeg
--WebAppBoundary--


### delete上传文件服务功能控制

DELETE http://localhost:8001/api/oss/delete?bucketName=oss-dev&fileName=test.xlsx


### 下载上传文件服务功能控制

GET http://localhost:8001/api/oss/download?bucketName=oss-dev&fileName=R-C.jpeg


